// src/components/Header.jsx
import { useEffect, useState } from 'react'
import './Header.css'

const navItems = [
  { id: 'home', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'skills', label: 'Skills' },
  { id: 'projects', label: 'Projects' },
  { id: 'cv', label: 'CV' },
]

const sections = ['home', 'about', 'skills', 'projects', 'cv']

export default function Header() {
  const [isMenuActive, setIsMenuActive] = useState(false)
  const [activeSection, setActiveSection] = useState('home')
  const [isScrolled, setIsScrolled] = useState(false)

  useEffect(() => {
    const onScroll = () => {
      setIsScrolled(window.scrollY > 60)
      const scrollPos = window.scrollY + 120
      for (const section of sections) {
        const el = document.getElementById(section)
        if (el) {
          const offset = el.offsetTop
          const height = el.offsetHeight
          if (scrollPos >= offset && scrollPos < offset + height) {
            setActiveSection(section)
            break
          }
        }
      }
    }
    onScroll()
    window.addEventListener('scroll', onScroll)
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const scrollTo = (sectionId) => {
    setIsMenuActive(false)
    const el = document.getElementById(sectionId)
    if (el) el.scrollIntoView({ behavior: 'smooth' })
  }

  return (
    <header className={`header${isScrolled ? ' scrolled' : ''}`}>
      <div className="header-inner">
        <div className="logo" onClick={() => scrollTo('home')}>
          <span className="logo-text gradient-text">Ahmed Emara</span>
          <span className="logo-title">Junior Software Engineer</span>
        </div>
        <nav className="nav">
          <ul className={`nav-list${isMenuActive ? ' active' : ''}`}>
            {navItems.map((item) => (
              <li key={item.id}>
                <a
                  onClick={() => scrollTo(item.id)}
                  className={activeSection === item.id ? 'active' : ''}
                >
                  {item.label}
                </a>
              </li>
            ))}
          </ul>
          <button
            className={`mobile-toggle${isMenuActive ? ' active' : ''}`}
            onClick={() => setIsMenuActive(!isMenuActive)}
            aria-label="Toggle menu"
          >
            <span></span>
            <span></span>
            <span></span>
          </button>
        </nav>
      </div>
    </header>
  )
}

// src/app/header/header.component.ts
import { Component, HostListener, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  standalone: true,
  imports: [CommonModule],
})
export class HeaderComponent implements OnInit, OnDestroy {
  isMenuActive = false;
  activeSection = 'home';
  isScrolled = false;

  private sections = ['home', 'about', 'skills', 'projects', 'cv'];

  navItems = [
    { id: 'home', label: 'Home' },
    { id: 'about', label: 'About' },
    { id: 'skills', label: 'Skills' },
    { id: 'projects', label: 'Projects' },
    { id: 'cv', label: 'CV' },
  ];

  ngOnInit() {
    this.onScroll();
  }

  @HostListener('window:scroll')
  onScroll() {
    this.isScrolled = window.scrollY > 60;
    const scrollPos = window.scrollY + 120;
    for (const section of this.sections) {
      const el = document.getElementById(section);
      if (el) {
        const offset = el.offsetTop;
        const height = el.offsetHeight;
        if (scrollPos >= offset && scrollPos < offset + height) {
          this.activeSection = section;
          break;
        }
      }
    }
  }

  toggleMenu() {
    this.isMenuActive = !this.isMenuActive;
  }

  closeMenu() {
    this.isMenuActive = false;
  }

  scrollTo(sectionId: string) {
    this.closeMenu();
    const el = document.getElementById(sectionId);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  }

  ngOnDestroy() {}
}

<header class="header-container">
    <div class="logo">
        <h1>Ahmed Emara</h1>
        <p>Junior Software Engineer</p>
    </div>
    <nav class="navigation">
        <ul [ngClass]="{'active': isMenuActive}" class="dropdown-menu">
            <li><a routerLink="/" routerLinkActive="active-link" (click)="toggleMenu()">Home</a></li>
            <li><a routerLink="/about" routerLinkActive="active-link" (click)="toggleMenu()">About</a></li>
            <li><a routerLink="/skills" routerLinkActive="active-link" (click)="toggleMenu()">Skills</a></li>
            <li><a routerLink="/projects" routerLinkActive="active-link" (click)="toggleMenu()">Projects</a></li>
        </ul>
    </nav>
    <div class="mobile-menu" (click)="toggleMenu()" [class.active]="isMenuActive"
        [attr.aria-expanded]="isMenuActive ? 'true' : 'false'">
        <i class="fas fa-bars"></i>
    </div>
</header>
