// src/app/hero/hero.component.ts
import { Component, OnInit, OnDestroy, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.scss'],
})
export class HeroComponent implements OnInit, OnDestroy {
  titles = [
    'Software Engineer',
    'Full-Stack Developer',
    'Problem Solver',
    'Tech Enthusiast',
  ];
  currentTitle = '';
  titleIndex = 0;
  charIndex = 0;
  isDeleting = false;
  private timeoutId: ReturnType<typeof setTimeout> | null = null;

  phase: 'start' | 'powerOn' | 'reveal' | 'idle' = 'start';
  showIntro = true;

  private mouseX = 0;
  private mouseY = 0;
  private robotAnimFrame: number | null = null;
  private introTimers: ReturnType<typeof setTimeout>[] = [];

  @HostListener('document:mousemove', ['$event'])
  onMouseMove(event: MouseEvent) {
    this.mouseX = event.clientX;
    this.mouseY = event.clientY;
  }

  ngOnInit() {
    this.typeEffect();
    this.runIntroSequence();
  }

  private runIntroSequence() {
    this.introTimers.push(setTimeout(() => {
      this.phase = 'powerOn';
    }, 600));

    this.introTimers.push(setTimeout(() => {
      this.phase = 'reveal';
      this.showIntro = false;
    }, 2600));

    this.introTimers.push(setTimeout(() => {
      this.phase = 'idle';
      this.startRobotTracking();
    }, 3600));
  }

  private startRobotTracking() {
    const track = () => {
      const robot = document.getElementById('robotHeadIdle');
      if (robot) {
        const rect = robot.getBoundingClientRect();
        const centerX = rect.left + rect.width / 2;
        const centerY = rect.top + rect.height / 2;

        const deltaX = this.mouseX - centerX;
        const deltaY = this.mouseY - centerY;

        const rotateY = Math.max(-18, Math.min(18, deltaX / 25));
        const rotateX = Math.max(-12, Math.min(12, -deltaY / 25));

        robot.style.transform = `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;
      }
      this.robotAnimFrame = requestAnimationFrame(track);
    };
    this.robotAnimFrame = requestAnimationFrame(track);
  }

  typeEffect() {
    const current = this.titles[this.titleIndex];

    if (this.isDeleting) {
      this.charIndex--;
      this.currentTitle = current.substring(0, this.charIndex);
      if (this.charIndex <= 0) {
        this.isDeleting = false;
        this.charIndex = 0;
        this.titleIndex = (this.titleIndex + 1) % this.titles.length;
        this.timeoutId = setTimeout(() => this.typeEffect(), 300);
        return;
      }
    } else {
      this.charIndex++;
      this.currentTitle = current.substring(0, this.charIndex);
      if (this.charIndex >= current.length) {
        this.isDeleting = true;
        this.timeoutId = setTimeout(() => this.typeEffect(), 2000);
        return;
      }
    }
    const speed = this.isDeleting ? 40 : 80;
    this.timeoutId = setTimeout(() => this.typeEffect(), speed);
  }

  scrollToAbout() {
    const el = document.getElementById('about');
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  }

  scrollToProjects() {
    const el = document.getElementById('projects');
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  }

  ngOnDestroy() {
    this.introTimers.forEach((t) => clearTimeout(t));
    if (this.timeoutId) clearTimeout(this.timeoutId);
    if (this.robotAnimFrame !== null) cancelAnimationFrame(this.robotAnimFrame);
  }
}

<section class="hero" id="home">
  <div class="orb orb-1"></div>
  <div class="orb orb-2"></div>
  <div class="orb orb-3"></div>

  <!-- INTRO OVERLAY -->
  <div class="intro-overlay" *ngIf="showIntro" [class.fade-out]="phase === 'reveal'">
    <div class="intro-robot" [class.powered]="phase === 'powerOn' || phase === 'reveal' || phase === 'idle'">
      <div class="robot-body">
        <div class="r-head">
          <div class="r-crest"></div>
          <div class="r-helmet">
            <div class="r-visor"></div>
            <div class="r-ear left"></div>
            <div class="r-ear right"></div>
            <div class="r-cheek left"></div>
            <div class="r-cheek right"></div>
            <div class="r-chin"></div>
            <div class="r-grill"></div>
          </div>
        </div>
        <div class="r-neck">
          <div class="r-neck-ring"></div>
        </div>
        <div class="r-torso">
          <div class="r-upper-plate"></div>
          <div class="r-arc-reactor">
            <div class="r-arc-core"></div>
            <div class="r-arc-ring"></div>
          </div>
          <div class="r-waist"></div>
          <div class="r-shoulder left"></div>
          <div class="r-shoulder right"></div>
          <div class="r-arm left">
            <div class="r-arm-upper"></div>
            <div class="r-arm-joint"></div>
          </div>
          <div class="r-arm right">
            <div class="r-arm-upper"></div>
            <div class="r-arm-joint"></div>
          </div>
        </div>
      </div>
      <div class="intro-glow-overlay"></div>
    </div>
    <div class="scan-line" [class.active]="phase === 'powerOn'"></div>
    <div class="power-flash" [class.active]="phase === 'powerOn'"></div>
    <div class="intro-text" [class.show]="phase === 'powerOn'">INITIALIZING...</div>
  </div>

  <!-- HERO LAYOUT (after intro) -->
  <div class="hero-layout" [class.visible]="phase === 'reveal' || phase === 'idle'">
    <!-- Left Column: Content -->
    <div class="hero-content-col">
      <div class="hero-content">
        <div class="profile-wrapper">
          <div class="profile-glow"></div>
          <img src="/images/ProfilePicture.png" alt="Ahmed Emara" class="profile-img" />
        </div>
        <h1 class="hero-name">
          Hi, I'm <span class="gradient-text">Ahmed Emara</span>
        </h1>
        <div class="typing-wrapper">
          <span class="typing-text">{{ currentTitle }}</span>
          <span class="cursor">|</span>
        </div>
        <p class="hero-tagline">
          Building scalable software solutions with modern technologies.
        </p>
        <div class="hero-actions">
          <button class="btn btn-primary" (click)="scrollToAbout()">
            About Me
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><polyline points="19 12 12 19 5 12"/></svg>
          </button>
          <button class="btn btn-outline" (click)="scrollToProjects()">
            View Projects
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
          </button>
        </div>
      </div>
    </div>

    <!-- Right Column: Robot -->
    <div class="hero-robot-col">
      <div class="robot-idle-wrapper" id="robotHeadIdle">
        <div class="robot-body">
          <div class="r-head">
            <div class="r-crest"></div>
            <div class="r-helmet">
              <div class="r-visor"></div>
              <div class="r-ear left"></div>
              <div class="r-ear right"></div>
              <div class="r-cheek left"></div>
              <div class="r-cheek right"></div>
              <div class="r-chin"></div>
              <div class="r-grill"></div>
            </div>
          </div>
          <div class="r-neck">
            <div class="r-neck-ring"></div>
          </div>
          <div class="r-torso">
            <div class="r-upper-plate"></div>
            <div class="r-arc-reactor">
              <div class="r-arc-core"></div>
              <div class="r-arc-ring"></div>
            </div>
            <div class="r-waist"></div>
            <div class="r-shoulder left"></div>
            <div class="r-shoulder right"></div>
            <div class="r-arm left">
              <div class="r-arm-upper"></div>
              <div class="r-arm-joint"></div>
            </div>
            <div class="r-arm right">
              <div class="r-arm-upper"></div>
              <div class="r-arm-joint"></div>
            </div>
          </div>
        </div>
        <div class="robot-idle-glow"></div>
      </div>
    </div>
  </div>

  <div class="scroll-indicator" *ngIf="phase === 'idle'">
    <div class="mouse">
      <div class="wheel"></div>
    </div>
  </div>
</section>

// src/components/Hero/Hero.jsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import './Hero.css'

const titles = [
  'Software Engineer',
  'Full-Stack Developer',
  'Problem Solver',
  'Tech Enthusiast',
]

export default function Hero() {
  const [currentTitle, setCurrentTitle] = useState('')
  const [titleIndex, setTitleIndex] = useState(0)
  const [charIndex, setCharIndex] = useState(0)
  const [isDeleting, setIsDeleting] = useState(false)
  const [typingActive, setTypingActive] = useState(false)
  const [contentReady, setContentReady] = useState(false)

  useEffect(() => {
    const c = setTimeout(() => setContentReady(true), 200)
    return () => clearTimeout(c)
  }, [])

  useEffect(() => {
    if (!contentReady) return
    const t = setTimeout(() => setTypingActive(true), 600)
    return () => clearTimeout(t)
  }, [contentReady])

  useEffect(() => {
    if (!typingActive) return
    const current = titles[titleIndex]
    let timeoutId

    if (isDeleting) {
      if (charIndex <= 0) {
        timeoutId = setTimeout(() => {
          setIsDeleting(false)
          setTitleIndex((prev) => (prev + 1) % titles.length)
        }, 300)
      } else {
        timeoutId = setTimeout(() => {
          setCharIndex((prev) => prev - 1)
          setCurrentTitle(current.substring(0, charIndex - 1))
        }, 40)
      }
    } else {
      if (charIndex >= current.length) {
        timeoutId = setTimeout(() => setIsDeleting(true), 2000)
      } else {
        timeoutId = setTimeout(() => {
          setCharIndex((prev) => prev + 1)
          setCurrentTitle(current.substring(0, charIndex + 1))
        }, 80)
      }
    }

    return () => clearTimeout(timeoutId)
  }, [charIndex, isDeleting, titleIndex, typingActive])

  const scrollTo = useCallback((id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })
  }, [])

  return (
    <section className="hero" id="home">
      <div className="hero-bg-glow" />

      <div className={`hero-layout${contentReady ? ' visible' : ''}`}>
        <div className={`hero-content-col${contentReady ? ' visible' : ''}`}>
          <div className="hero-content">
            <div className="profile-wrapper">
              <img src="/images/ProfilePicture.png" alt="Ahmed Emara" className="profile-img" />
            </div>
            <h1 className="hero-greeting">
              Hi, I&apos;m <span className="gradient-text">Ahmed Emara</span>
            </h1>
            <div className="typing-wrapper">
              <span className="typing-text">{currentTitle}</span>
              <span className="cursor">|</span>
            </div>
            <p className="hero-tagline">
              Building scalable software solutions with modern technologies.
            </p>
            <div className="hero-actions">
              <button className="btn btn-primary" onClick={() => scrollTo('about')}>
                About Me
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19" /><polyline points="19 12 12 19 5 12" /></svg>
              </button>
              <button className="btn btn-outline" onClick={() => scrollTo('projects')}>
                View Projects
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12" /><polyline points="12 5 19 12 12 19" /></svg>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="scroll-indicator">
        <div className="mouse">
          <div className="wheel"></div>
        </div>
      </div>
    </section>
  )
}
