// src/app/skills/skills.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ScrollAnimateDirective } from '../scroll-animate.directive';

@Component({
  selector: 'app-skills',
  standalone: true,
  imports: [CommonModule, ScrollAnimateDirective],
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss'],
})
export class SkillsComponent {
  skillCategories = [
    {
      name: 'Programming Languages',
      icon: 'fa-code',
      skills: [
        { name: 'Python', level: 90 },
        { name: 'JavaScript', level: 85 },
        { name: 'TypeScript', level: 80 },
        { name: 'Java', level: 75 },
        { name: 'C#', level: 70 },
        { name: 'Kotlin', level: 65 },
      ],
    },
    {
      name: 'Frameworks & Libraries',
      icon: 'fa-cubes',
      skills: [
        { name: 'React', level: 85 },
        { name: 'Angular', level: 85 },
        { name: 'Django', level: 80 },
        { name: 'FastAPI', level: 75 },
        { name: 'Flask', level: 75 },
        { name: 'ASP.NET Core', level: 70 },
        { name: 'Express.js', level: 75 },
        { name: 'Flutter', level: 60 },
      ],
    },
    {
      name: 'Web Technologies',
      icon: 'fa-globe',
      skills: [
        { name: 'HTML5', level: 95 },
        { name: 'CSS3', level: 90 },
        { name: 'SCSS', level: 85 },
        { name: 'Bootstrap', level: 80 },
        { name: 'Responsive Design', level: 90 },
        { name: 'JSON', level: 85 },
      ],
    },
    {
      name: 'API Technologies',
      icon: 'fa-plug',
      skills: [
        { name: 'REST APIs', level: 90 },
        { name: 'GraphQL', level: 70 },
      ],
    },
    {
      name: 'Databases',
      icon: 'fa-database',
      skills: [
        { name: 'PostgreSQL', level: 80 },
        { name: 'MySQL', level: 80 },
        { name: 'MongoDB', level: 70 },
      ],
    },
    {
      name: 'AI & ML Tools',
      icon: 'fa-brain',
      skills: [
        { name: 'Prompt Engineering', level: 85 },
        { name: 'Generative AI', level: 80 },
        { name: 'OpenAI API', level: 80 },
        { name: 'LangChain', level: 75 },
        { name: 'RAG', level: 70 },
      ],
    },
    {
      name: 'DevOps & Tools',
      icon: 'fa-cloud',
      skills: [
        { name: 'Git', level: 90 },
        { name: 'Docker', level: 80 },
        { name: 'AWS (EC2, S3, IAM, RDS, Lambda)', level: 75 },
        { name: 'Linux', level: 80 },
        { name: 'CI/CD', level: 75 },
        { name: 'Jenkins', level: 65 },
        { name: 'Agile Methodology', level: 80 },
      ],
    },
    {
      name: 'Architecture & Design',
      icon: 'fa-sitemap',
      skills: [
        { name: 'Microservices', level: 75 },
        { name: 'MVC', level: 85 },
        { name: 'REST Design', level: 85 },
        { name: 'Clean Architecture', level: 80 },
        { name: 'JWT Authentication', level: 85 },
        { name: 'RBAC', level: 80 },
        { name: 'Design Patterns', level: 75 },
      ],
    },
    {
      name: 'Soft Skills',
      icon: 'fa-users',
      skills: [
        { name: 'Communication', level: 90 },
        { name: 'Problem Solving', level: 95 },
        { name: 'Teamwork', level: 85 },
        { name: 'Adaptability', level: 85 },
        { name: 'Time Management', level: 80 },
        { name: 'Leadership', level: 75 },
      ],
    },
  ];

  trackByFn(index: number) {
    return index;
  }
}

<section class="skills" id="skills">
  <div class="container">
    <h2 class="section-title" appScrollAnimate>Skills & Expertise</h2>
    <p class="section-subtitle" appScrollAnimate>
      Technologies and tools I've worked with throughout my academic and professional journey.
    </p>

    <div class="skills-grid">
      <div
        class="skill-category glass"
        *ngFor="let category of skillCategories; let i = index"
        [style.transition-delay]="i * 0.1 + 's'"
        appScrollAnimate
      >
        <div class="category-header">
          <i class="fas {{ category.icon }}"></i>
          <h3>{{ category.name }}</h3>
        </div>
        <div class="skill-items">
          <div class="skill-item" *ngFor="let skill of category.skills">
            <div class="skill-info">
              <span class="skill-name">{{ skill.name }}</span>
              <span class="skill-level">{{ skill.level }}%</span>
            </div>
            <div class="progress-track">
              <div
                class="progress-fill"
                [style.width.%]="skill.level"
              ></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// src/components/Skills/Skills.jsx
'use client'

import { useScrollReveal } from '../../hooks/useScrollReveal'
import './Skills.css'

const skillCategories = [
  {
    name: 'Programming Languages',
    icon: 'fa-code',
    skills: ['Python', 'JavaScript', 'TypeScript', 'Java', 'C#', 'Kotlin'],
  },
  {
    name: 'Frameworks & Libraries',
    icon: 'fa-cubes',
    skills: ['React', 'Angular', 'Django', 'FastAPI', 'Flask', 'ASP.NET Core', 'Express.js', 'Flutter'],
  },
  {
    name: 'Web Technologies',
    icon: 'fa-globe',
    skills: ['HTML5', 'CSS3', 'SCSS', 'Bootstrap', 'Responsive Design', 'JSON'],
  },
  {
    name: 'API Technologies',
    icon: 'fa-plug',
    skills: ['REST APIs', 'GraphQL'],
  },
  {
    name: 'Databases',
    icon: 'fa-database',
    skills: ['PostgreSQL', 'MySQL', 'MongoDB'],
  },
  {
    name: 'AI & ML Tools',
    icon: 'fa-brain',
    skills: ['Prompt Engineering', 'Generative AI', 'OpenAI API', 'LangChain', 'RAG'],
  },
  {
    name: 'DevOps & Tools',
    icon: 'fa-cloud',
    skills: ['Git', 'Docker', 'AWS (EC2, S3, IAM, RDS, Lambda)', 'Linux', 'CI/CD', 'Jenkins', 'Agile Methodology'],
  },
  {
    name: 'Architecture & Design',
    icon: 'fa-sitemap',
    skills: ['Microservices', 'MVC', 'REST Design', 'Clean Architecture', 'JWT Authentication', 'RBAC', 'Design Patterns'],
  },
  {
    name: 'Soft Skills',
    icon: 'fa-users',
    skills: ['Communication', 'Problem Solving', 'Teamwork', 'Adaptability', 'Time Management', 'Leadership'],
  },
]

export default function Skills() {
  const titleRef = useScrollReveal()
  const subtitleRef = useScrollReveal()

  return (
    <section className="skills" id="skills">
      <div className="container">
        <h2 className="section-title" ref={titleRef}>Skills & Expertise</h2>
        <p className="section-subtitle" ref={subtitleRef}>
          Technologies and tools I've worked with throughout my academic and professional journey.
        </p>

        <div className="skills-grid">
          {skillCategories.map((category, i) => (
            <SkillCategoryCard key={i} category={category} index={i} />
          ))}
        </div>
      </div>
    </section>
  )
}

function SkillCategoryCard({ category, index }) {
  const ref = useScrollReveal()

  return (
    <div
      className="skill-category glass"
      ref={ref}
      style={{ transitionDelay: `${index * 0.1}s` }}
    >
      <div className="category-header">
        <i className={`fas ${category.icon}`}></i>
        <h3>{category.name}</h3>
      </div>
      <div className="skill-tags">
        {category.skills.map((skill, j) => (
          <span className="skill-tag" key={j}>{skill}</span>
        ))}
      </div>
    </div>
  )
}
